### ISSUE TITLE
No S4.exe 

### ISSUE THREAD

**Issue by zjw-asu** [sbyrnes321/metalens#1]
Hi, 

I find there is no S4.exe available on the link provided here. In fact, it seems S4.exe cannot be obtained  from their website anymore. I have tried to compile their makefile with their tutor guide, full of mistakes. Can I have a copy of your  .exe if possible ?

**Comment by sbyrnes321** [comment]
Try  http://sjbyrnes.com/S4.exe It might be an old version, I forget when I downloaded it.
